import React, { useState, useEffect } from 'react';
import { 
  BookOpen, 
  Users, 
  Calendar, 
  FileText, 
  TrendingUp, 
  Clock, 
  AlertCircle,
  CheckCircle,
  PlusCircle,
  Download,
  Share2,
  Settings
} from 'lucide-react';
import IEPProgressTracking from '../components/IEPProgressTracking';
import { AutoGeneratedIEP } from '../components/AutoGeneratedIEP';
import EnhancedIEPSharingSystem from '../components/EnhancedIEPSharingSystem';
import EvaluationRequestSystem from '../components/EvaluationRequestSystem';
import DigitalConsentForms from '../components/DigitalConsentForms';
import IEPDocumentViewer from '../components/IEPDocumentViewer';

interface IEPDashboardData {
  activeGoals: number;
  completedGoals: number;
  upcomingMeetings: number;
  pendingEvaluations: number;
  lastUpdated: string;
  nextMeeting?: {
    date: string;
    type: string;
    participants: string[];
  };
  recentProgress: {
    goalTitle: string;
    progress: number;
    change: number;
  }[];
  alerts: {
    id: string;
    type: 'warning' | 'info' | 'success';
    message: string;
    date: string;
  }[];
}

interface IEPDashboardProps {
  childId: string;
}

const IEPDashboard: React.FC<IEPDashboardProps> = ({ childId }) => {
  const [activeTab, setActiveTab] = useState<'overview' | 'progress' | 'documents' | 'consent' | 'sharing' | 'evaluations'>('overview');
  const [dashboardData, setDashboardData] = useState<IEPDashboardData | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    loadDashboardData();
  }, [childId]);

  const loadDashboardData = async () => {
    try {
      setLoading(true);
      // Mock data - replace with actual API call
      const mockData: IEPDashboardData = {
        activeGoals: 8,
        completedGoals: 3,
        upcomingMeetings: 2,
        pendingEvaluations: 1,
        lastUpdated: '2025-11-01',
        nextMeeting: {
          date: '2025-11-15',
          type: 'Annual Review',
          participants: ['Parent', 'General Ed Teacher', 'Special Ed Teacher', 'Speech Therapist']
        },
        recentProgress: [
          { goalTitle: 'Reading Comprehension', progress: 75, change: 15 },
          { goalTitle: 'Social Interaction', progress: 45, change: 10 },
          { goalTitle: 'Math Problem Solving', progress: 85, change: 20 }
        ],
        alerts: [
          {
            id: '1',
            type: 'warning',
            message: 'Annual IEP review meeting scheduled for November 15th',
            date: '2025-11-01'
          },
          {
            id: '2',
            type: 'info',
            message: 'New evaluation report available for review',
            date: '2025-10-28'
          },
          {
            id: '3',
            type: 'success',
            message: 'Reading comprehension goal milestone achieved',
            date: '2025-10-25'
          }
        ]
      };
      setDashboardData(mockData);
    } catch (error) {
      console.error('Error loading dashboard data:', error);
    } finally {
      setLoading(false);
    }
  };

  const getAlertIcon = (type: string) => {
    switch (type) {
      case 'warning': return <AlertCircle className="w-5 h-5 text-yellow-500" />;
      case 'success': return <CheckCircle className="w-5 h-5 text-green-500" />;
      default: return <AlertCircle className="w-5 h-5 text-blue-500" />;
    }
  };

  const getAlertBgColor = (type: string) => {
    switch (type) {
      case 'warning': return 'bg-yellow-50 border-yellow-200';
      case 'success': return 'bg-green-50 border-green-200';
      default: return 'bg-blue-50 border-blue-200';
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center p-8">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-coral-500"></div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-3xl font-bold text-gray-900">IEP Management</h1>
          <p className="text-gray-600">Comprehensive IEP tracking and management</p>
        </div>
        <div className="flex gap-3">
          <button 
            onClick={() => alert('IEP Settings - Feature coming soon!')}
            className="inline-flex items-center px-4 py-2 border border-gray-300 rounded-lg text-sm font-medium text-gray-700 bg-white hover:bg-gray-50 transition-colors"
          >
            <Settings className="w-4 h-4 mr-2" />
            Settings
          </button>
          <button 
            onClick={() => alert('IEP Export - Feature coming soon!')}
            className="inline-flex items-center px-4 py-2 bg-coral-500 text-white rounded-lg text-sm font-medium hover:bg-coral-600 transition-colors"
          >
            <Download className="w-4 h-4 mr-2" />
            Export IEP
          </button>
        </div>
      </div>

      {/* Navigation Tabs */}
      <div className="border-b border-gray-200">
        <nav className="flex space-x-8">
          {[
            { id: 'overview', label: 'Overview', icon: BookOpen },
            { id: 'progress', label: 'Progress Tracking', icon: TrendingUp },
            { id: 'documents', label: 'Documents', icon: FileText },
            { id: 'consent', label: 'Consent Forms', icon: Settings },
            { id: 'sharing', label: 'Sharing', icon: Share2 },
            { id: 'evaluations', label: 'Evaluations', icon: Users }
          ].map(tab => {
            const Icon = tab.icon;
            return (
              <button
                key={tab.id}
                onClick={() => setActiveTab(tab.id as any)}
                className={`flex items-center px-1 py-4 text-sm font-medium border-b-2 transition-colors ${
                  activeTab === tab.id
                    ? 'border-coral-500 text-coral-600'
                    : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'
                }`}
              >
                <Icon className="w-4 h-4 mr-2" />
                {tab.label}
              </button>
            );
          })}
        </nav>
      </div>

      {/* Tab Content */}
      {activeTab === 'overview' && dashboardData && (
        <div className="space-y-6">
          {/* Stats Cards */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            <div className="bg-white p-6 rounded-xl border border-gray-200">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm font-medium text-gray-600">Active Goals</p>
                  <p className="text-2xl font-bold text-gray-900">{dashboardData.activeGoals}</p>
                </div>
                <div className="p-3 bg-coral-100 rounded-lg">
                  <TrendingUp className="w-6 h-6 text-coral-600" />
                </div>
              </div>
            </div>

            <div className="bg-white p-6 rounded-xl border border-gray-200">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm font-medium text-gray-600">Completed Goals</p>
                  <p className="text-2xl font-bold text-gray-900">{dashboardData.completedGoals}</p>
                </div>
                <div className="p-3 bg-green-100 rounded-lg">
                  <CheckCircle className="w-6 h-6 text-green-600" />
                </div>
              </div>
            </div>

            <div className="bg-white p-6 rounded-xl border border-gray-200">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm font-medium text-gray-600">Upcoming Meetings</p>
                  <p className="text-2xl font-bold text-gray-900">{dashboardData.upcomingMeetings}</p>
                </div>
                <div className="p-3 bg-blue-100 rounded-lg">
                  <Calendar className="w-6 h-6 text-blue-600" />
                </div>
              </div>
            </div>

            <div className="bg-white p-6 rounded-xl border border-gray-200">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm font-medium text-gray-600">Pending Evaluations</p>
                  <p className="text-2xl font-bold text-gray-900">{dashboardData.pendingEvaluations}</p>
                </div>
                <div className="p-3 bg-yellow-100 rounded-lg">
                  <Users className="w-6 h-6 text-yellow-600" />
                </div>
              </div>
            </div>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            {/* Next Meeting */}
            {dashboardData.nextMeeting && (
              <div className="bg-white p-6 rounded-xl border border-gray-200">
                <h3 className="text-lg font-semibold text-gray-900 mb-4">Next IEP Meeting</h3>
                <div className="space-y-3">
                  <div className="flex items-center gap-3">
                    <Calendar className="w-5 h-5 text-gray-500" />
                    <span className="text-gray-700">
                      {new Date(dashboardData.nextMeeting.date).toLocaleDateString('en-US', {
                        weekday: 'long',
                        year: 'numeric',
                        month: 'long',
                        day: 'numeric'
                      })}
                    </span>
                  </div>
                  <div className="flex items-center gap-3">
                    <FileText className="w-5 h-5 text-gray-500" />
                    <span className="text-gray-700">{dashboardData.nextMeeting.type}</span>
                  </div>
                  <div className="flex items-center gap-3">
                    <Users className="w-5 h-5 text-gray-500" />
                    <span className="text-gray-700">
                      {dashboardData.nextMeeting.participants.length} participants
                    </span>
                  </div>
                  <button 
                    onClick={() => alert('Meeting details - Feature coming soon!')}
                    className="w-full mt-4 px-4 py-2 bg-coral-500 text-white rounded-lg hover:bg-coral-600 transition-colors"
                  >
                    View Meeting Details
                  </button>
                </div>
              </div>
            )}

            {/* Recent Progress */}
            <div className="bg-white p-6 rounded-xl border border-gray-200">
              <h3 className="text-lg font-semibold text-gray-900 mb-4">Recent Progress</h3>
              <div className="space-y-4">
                {dashboardData.recentProgress.map((item, index) => (
                  <div key={index} className="flex items-center justify-between">
                    <div>
                      <p className="font-medium text-gray-900">{item.goalTitle}</p>
                      <p className="text-sm text-gray-600">{item.progress}% complete</p>
                    </div>
                    <div className="flex items-center gap-2">
                      <span className={`text-sm font-medium ${
                        item.change > 0 ? 'text-green-600' : 'text-red-600'
                      }`}>
                        {item.change > 0 ? '+' : ''}{item.change}%
                      </span>
                      <div className="w-16 h-2 bg-gray-200 rounded-full">
                        <div
                          className="h-2 bg-coral-500 rounded-full transition-all"
                          style={{ width: `${item.progress}%` }}
                        />
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* Alerts */}
          <div className="bg-white rounded-xl border border-gray-200 p-6">
            <h3 className="text-lg font-semibold text-gray-900 mb-4">Recent Alerts</h3>
            <div className="space-y-3">
              {dashboardData.alerts.map(alert => (
                <div
                  key={alert.id}
                  className={`p-4 rounded-lg border flex items-start gap-3 ${getAlertBgColor(alert.type)}`}
                >
                  {getAlertIcon(alert.type)}
                  <div className="flex-1">
                    <p className="text-gray-900">{alert.message}</p>
                    <p className="text-sm text-gray-600 mt-1">
                      {new Date(alert.date).toLocaleDateString()}
                    </p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}

      {activeTab === 'progress' && (
        <IEPProgressTracking childId={childId} />
      )}

      {activeTab === 'documents' && (
        <IEPDocumentViewer childId={childId} />
      )}

      {activeTab === 'consent' && (
        <DigitalConsentForms childId={childId} />
      )}

      {activeTab === 'sharing' && (
        <EnhancedIEPSharingSystem childId={childId} />
      )}

      {activeTab === 'evaluations' && (
        <EvaluationRequestSystem childId={childId} />
      )}
    </div>
  );
};

export default IEPDashboard;