import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  Brain,
  Target,
  BookOpen,
  Users,
  Settings,
  CheckCircle,
  AlertTriangle,
  Lightbulb,
  Wand2,
  Download,
  Edit,
  Eye,
  ArrowRight,
  BarChart3,
  FileText,
  Sparkles,
  Clock
} from 'lucide-react';
import { Button } from '@aivo/ui';
import { BaselineAssessment, IEPDocument, IEPGoal, Accommodation, Service } from '../types/iep.types';

interface AutoGeneratedIEPProps {
  baselineAssessment: BaselineAssessment;
  onSaveIEP: (iep: Partial<IEPDocument>) => void;
  onPreviewIEP: (iep: Partial<IEPDocument>) => void;
  onClose: () => void;
}

interface AIRecommendation {
  type: 'goal' | 'accommodation' | 'service';
  confidence: number;
  reasoning: string;
  data: IEPGoal | Accommodation | Service;
}

export const AutoGeneratedIEP: React.FC<AutoGeneratedIEPProps> = ({
  baselineAssessment,
  onSaveIEP,
  onPreviewIEP,
  onClose
}) => {
  const [currentStep, setCurrentStep] = useState<'analysis' | 'recommendations' | 'customize' | 'review'>('analysis');
  const [isGenerating, setIsGenerating] = useState(false);
  const [aiRecommendations, setAiRecommendations] = useState<AIRecommendation[]>([]);
  const [selectedRecommendations, setSelectedRecommendations] = useState<Set<number>>(new Set());
  const [customizations, setCustomizations] = useState<{
    goals: IEPGoal[];
    accommodations: Accommodation[];
    services: Service[];
  }>({
    goals: [],
    accommodations: [],
    services: []
  });

  const extendedAssessment = baselineAssessment as BaselineAssessment & {
    studentName?: string;
    completedDate?: string;
    overallScore?: number;
    domains?: { name: string; score: number }[];
  };

  const academicDomainSummaries = extendedAssessment.domains ??
    Object.entries(baselineAssessment.academicLevels).map(([domainName, level]) => ({
      name: domainName.charAt(0).toUpperCase() + domainName.slice(1),
      score: Math.round(Math.min(1, Math.max(0, level / 4)) * 100)
    }));

  const displayedStudentName = extendedAssessment.studentName ?? baselineAssessment.childId;
  const displayedAssessmentDate = extendedAssessment.completedDate ?? baselineAssessment.assessmentDate;
  const displayedOverallScore = extendedAssessment.overallScore ?? Math.round(
    academicDomainSummaries.reduce((total, domain) => total + domain.score, 0) /
      Math.max(1, academicDomainSummaries.length)
  );

  // Mock AI analysis based on baseline assessment
  const generateRecommendations = async () => {
    setIsGenerating(true);
    
    // Simulate AI processing
    await new Promise(resolve => setTimeout(resolve, 3000));

    const mockRecommendations: AIRecommendation[] = [
      {
        type: 'goal',
        confidence: 0.92,
        reasoning: 'Reading comprehension scores indicate the need for sustained literacy intervention.',
        data: {
          id: 'goal-1',
          domain: 'academic',
          category: 'Reading Comprehension',
          description: 'Improve accuracy and understanding when reading grade-level passages.',
          measurableObjective: 'When given grade-level reading passages, the student will answer comprehension questions with 80% accuracy.',
          targetCriteria: '80% accuracy across three consecutive weekly assessments',
          evaluationMethod: 'Weekly reading assessments and annotated work samples',
          frequency: 'Daily',
          startDate: new Date().toISOString(),
          targetDate: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString(),
          currentProgress: 0,
          status: 'not-started',
          notes: [],
          dataPoints: []
        }
      },
      {
        type: 'goal',
        confidence: 0.88,
        reasoning: 'Number operations performance suggests a focus on foundational computation skills.',
        data: {
          id: 'goal-2',
          domain: 'academic',
          category: 'Mathematics Problem Solving',
          description: 'Build fluency with addition and subtraction involving regrouping.',
          measurableObjective: 'When presented with multi-step addition and subtraction problems, the student will solve them with 80% accuracy.',
          targetCriteria: '80% accuracy in four consecutive progress-monitoring probes',
          evaluationMethod: 'Curriculum-based measurements and teacher-collected data',
          frequency: 'Daily',
          startDate: new Date().toISOString(),
          targetDate: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString(),
          currentProgress: 0,
          status: 'not-started',
          notes: [],
          dataPoints: []
        }
      },
      {
        type: 'accommodation',
        confidence: 0.85,
        reasoning: 'Processing speed considerations point to the benefit of additional time and pacing supports.',
        data: {
          id: 'acc-1',
          type: 'assessment',
          category: 'Timing and Scheduling',
          description: 'Extended time for assignments and assessments',
          implementation: 'Provide 1.5x standard time for tests and major assignments with planned checkpoints.',
          frequency: 'as-needed',
          subjects: ['All subjects'],
          effectiveness: 'not-assessed',
          notes: 'Recommended to support sustained attention during longer tasks.'
        }
      },
      {
        type: 'accommodation',
        confidence: 0.9,
        reasoning: 'Reading comprehension challenges warrant alternative presentation formats.',
        data: {
          id: 'acc-2',
          type: 'instructional',
          category: 'Presentation',
          description: 'Text-to-speech and highlighted key vocabulary supports',
          implementation: 'Use assistive technology for grade-level texts and provide pre-highlighted vocabulary lists.',
          frequency: 'always',
          subjects: ['ELA', 'Science', 'Social Studies'],
          effectiveness: 'not-assessed',
          notes: 'Ensures access to grade-level content while decoding skills strengthen.'
        }
      },
      {
        type: 'service',
        confidence: 0.87,
        reasoning: 'Cross-domain needs support specialized academic instruction to reinforce literacy and numeracy goals.',
        data: {
          id: 'service-1',
          type: 'special-education',
          serviceName: 'Specialized Academic Instruction',
          provider: 'Special Education Teacher',
          frequency: '5 times per week',
          duration: '45 minutes',
          location: 'special-classroom',
          startDate: new Date().toISOString(),
          endDate: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString(),
          goals: ['goal-1', 'goal-2']
        }
      },
      {
        type: 'service',
        confidence: 0.75,
        reasoning: 'Language processing data indicates value in targeted speech-language intervention.',
        data: {
          id: 'service-2',
          type: 'speech-therapy',
          serviceName: 'Speech-Language Therapy',
          provider: 'Speech-Language Pathologist',
          frequency: '2 times per week',
          duration: '30 minutes',
          location: 'therapy-room',
          startDate: new Date().toISOString(),
          endDate: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString(),
          goals: ['goal-1']
        }
      }
    ];

    setAiRecommendations(mockRecommendations);
    setSelectedRecommendations(new Set(mockRecommendations.map((_, index) => index)));
    setIsGenerating(false);
    setCurrentStep('recommendations');
  };

  const toggleRecommendation = (index: number) => {
    const newSelected = new Set(selectedRecommendations);
    if (newSelected.has(index)) {
      newSelected.delete(index);
    } else {
      newSelected.add(index);
    }
    setSelectedRecommendations(newSelected);
  };

  const generateIEPDocument = (): Partial<IEPDocument> => {
    const selectedItems = Array.from(selectedRecommendations).map(index => aiRecommendations[index]);
    
    const goals = selectedItems.filter(item => item.type === 'goal').map(item => item.data as IEPGoal);
    const accommodations = selectedItems.filter(item => item.type === 'accommodation').map(item => item.data as Accommodation);
    const services = selectedItems.filter(item => item.type === 'service').map(item => item.data as Service);

    return {
      childId: baselineAssessment.childId,
      goals: [...goals, ...customizations.goals],
      accommodations: [...accommodations, ...customizations.accommodations],
      services: [...services, ...customizations.services],
      effectiveDate: new Date().toISOString(),
      reviewDate: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString(),
      status: 'draft',
      source: 'auto-generated'
    };
  };

  const getConfidenceColor = (confidence: number) => {
    if (confidence >= 0.9) return 'text-green-600 bg-green-100';
    if (confidence >= 0.8) return 'text-blue-600 bg-blue-100';
    if (confidence >= 0.7) return 'text-amber-600 bg-amber-100';
    return 'text-red-600 bg-red-100';
  };

  const getConfidenceLabel = (confidence: number) => {
    if (confidence >= 0.9) return 'High Confidence';
    if (confidence >= 0.8) return 'Good Confidence';
    if (confidence >= 0.7) return 'Moderate';
    return 'Low Confidence';
  };

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
      <motion.div
        initial={{ opacity: 0, scale: 0.95 }}
        animate={{ opacity: 1, scale: 1 }}
        exit={{ opacity: 0, scale: 0.95 }}
        className="bg-white rounded-2xl shadow-2xl w-full max-w-6xl max-h-[90vh] overflow-hidden"
      >
        {/* Header */}
        <div className="bg-gradient-to-r from-purple-600 via-pink-600 to-coral-500 text-white p-6">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="bg-white/20 rounded-full p-2">
                <Sparkles className="w-6 h-6" />
              </div>
              <div>
                <h2 className="text-2xl font-bold">AI-Generated IEP</h2>
                <p className="text-white/90">Based on baseline assessment results</p>
              </div>
            </div>
            <Button
              variant="ghost"
              onClick={onClose}
              className="text-white hover:bg-white/10"
            >
              ✕
            </Button>
          </div>
        </div>

        {/* Progress Steps */}
        <div className="bg-gray-50 px-6 py-4">
          <div className="flex items-center justify-center space-x-8">
            {[
              { step: 'analysis', label: 'Analysis', icon: Brain },
              { step: 'recommendations', label: 'AI Recommendations', icon: Wand2 },
              { step: 'customize', label: 'Customize', icon: Edit },
              { step: 'review', label: 'Review', icon: Eye }
            ].map(({ step, label, icon: Icon }, index) => (
              <div key={step} className="flex items-center">
                <div className={`flex items-center gap-2 ${
                  currentStep === step ? 'text-purple-600' : 
                  ['analysis', 'recommendations', 'customize', 'review'].indexOf(currentStep) > index ? 'text-green-600' : 'text-gray-400'
                }`}>
                  <div className={`w-8 h-8 rounded-full flex items-center justify-center ${
                    currentStep === step ? 'bg-purple-100' :
                    ['analysis', 'recommendations', 'customize', 'review'].indexOf(currentStep) > index ? 'bg-green-100' : 'bg-gray-100'
                  }`}>
                    <Icon className="w-4 h-4" />
                  </div>
                  <span className="font-medium">{label}</span>
                </div>
                {index < 3 && (
                  <div className={`w-8 h-px ml-4 ${
                    ['analysis', 'recommendations', 'customize', 'review'].indexOf(currentStep) > index ? 'bg-green-300' : 'bg-gray-300'
                  }`} />
                )}
              </div>
            ))}
          </div>
        </div>

        {/* Content */}
        <div className="p-6 overflow-y-auto max-h-[60vh]">
          {currentStep === 'analysis' && (
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              className="space-y-6"
            >
              <div className="text-center">
                <Brain className="w-16 h-16 text-purple-500 mx-auto mb-4" />
                <h3 className="text-2xl font-bold text-gray-900 mb-2">Baseline Assessment Analysis</h3>
                <p className="text-gray-600 max-w-2xl mx-auto">
                  Our AI system will analyze the baseline assessment results to generate personalized IEP recommendations 
                  tailored to your child's specific needs and learning profile.
                </p>
              </div>

              {/* Assessment Summary */}
              <div className="bg-gradient-to-r from-blue-50 to-purple-50 rounded-xl p-6 border border-blue-200">
                <h4 className="text-lg font-semibold text-gray-900 mb-4">Assessment Overview</h4>
                <div className="grid md:grid-cols-2 gap-4">
                  <div>
                    <span className="text-sm font-medium text-gray-700">Student:</span>
                    <p className="text-gray-900">{displayedStudentName}</p>
                  </div>
                  <div>
                    <span className="text-sm font-medium text-gray-700">Assessment Date:</span>
                    <p className="text-gray-900">{new Date(displayedAssessmentDate).toLocaleDateString()}</p>
                  </div>
                  <div>
                    <span className="text-sm font-medium text-gray-700">Overall Score:</span>
                    <p className="text-gray-900">{displayedOverallScore}/100</p>
                  </div>
                  <div>
                    <span className="text-sm font-medium text-gray-700">Areas Assessed:</span>
                    <p className="text-gray-900">{academicDomainSummaries.length} domains</p>
                  </div>
                </div>
              </div>

              {/* Key Findings */}
              <div className="grid md:grid-cols-3 gap-4">
                {academicDomainSummaries.slice(0, 3).map((domain) => (
                  <div key={domain.name} className="bg-white border border-gray-200 rounded-xl p-4">
                    <div className="flex items-center gap-2 mb-2">
                      <BarChart3 className="w-5 h-5 text-coral-500" />
                      <h5 className="font-semibold text-gray-900">{domain.name}</h5>
                    </div>
                    <p className="text-2xl font-bold text-gray-900 mb-1">{domain.score}%</p>
                    <p className="text-sm text-gray-600">
                      {domain.score >= 70 ? 'Adequate' : domain.score >= 50 ? 'Needs Support' : 'Significant Need'}
                    </p>
                  </div>
                ))}
              </div>

              {!isGenerating && (
                <div className="text-center">
                  <Button
                    variant="gradient"
                    onClick={generateRecommendations}
                    className="flex items-center gap-2 px-8 py-3"
                  >
                    <Sparkles className="w-5 h-5" />
                    Generate AI Recommendations
                  </Button>
                </div>
              )}

              {isGenerating && (
                <div className="text-center py-8">
                  <div className="inline-flex items-center gap-3 bg-purple-50 rounded-full px-6 py-3 border border-purple-200">
                    <div className="animate-spin rounded-full h-5 w-5 border-2 border-purple-600 border-t-transparent"></div>
                    <span className="text-purple-700 font-medium">Analyzing assessment data...</span>
                  </div>
                  <p className="text-gray-600 mt-3 text-sm">This may take a few moments</p>
                </div>
              )}
            </motion.div>
          )}

          {currentStep === 'recommendations' && (
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              className="space-y-6"
            >
              <div className="text-center mb-6">
                <Lightbulb className="w-12 h-12 text-amber-500 mx-auto mb-4" />
                <h3 className="text-xl font-bold text-gray-900 mb-2">AI-Generated Recommendations</h3>
                <p className="text-gray-600">
                  Review and select the recommendations you'd like to include in the IEP.
                </p>
              </div>

              <div className="space-y-4">
                {aiRecommendations.map((recommendation, index) => (
                  <motion.div
                    key={index}
                    initial={{ opacity: 0, x: -20 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: index * 0.1 }}
                    className={`border-2 rounded-xl p-4 transition-all ${
                      selectedRecommendations.has(index)
                        ? 'border-purple-300 bg-purple-50'
                        : 'border-gray-200 bg-white hover:border-gray-300'
                    }`}
                  >
                    <div className="flex items-start gap-4">
                      <input
                        type="checkbox"
                        checked={selectedRecommendations.has(index)}
                        onChange={() => toggleRecommendation(index)}
                        className="mt-1 w-5 h-5 text-purple-600 border-gray-300 rounded focus:ring-purple-500"
                      />
                      
                      <div className="flex-1">
                        <div className="flex items-center gap-3 mb-2">
                          <span className={`px-3 py-1 rounded-full text-sm font-medium ${
                            recommendation.type === 'goal' ? 'bg-blue-100 text-blue-800' :
                            recommendation.type === 'accommodation' ? 'bg-green-100 text-green-800' :
                            'bg-purple-100 text-purple-800'
                          }`}>
                            {recommendation.type.charAt(0).toUpperCase() + recommendation.type.slice(1)}
                          </span>
                          
                          <span className={`px-2 py-1 rounded-full text-xs font-medium ${getConfidenceColor(recommendation.confidence)}`}>
                            {getConfidenceLabel(recommendation.confidence)} ({Math.round(recommendation.confidence * 100)}%)
                          </span>
                        </div>

                        <h4 className="font-semibold text-gray-900 mb-2">
                          {recommendation.type === 'goal' && `${(recommendation.data as IEPGoal).category} Goal`}
                          {recommendation.type === 'accommodation' && (recommendation.data as Accommodation).description}
                          {recommendation.type === 'service' && (recommendation.data as Service).serviceName}
                        </h4>

                        <p className="text-gray-700 mb-3">{recommendation.reasoning}</p>

                        {recommendation.type === 'goal' && (
                          <div className="bg-gray-50 rounded-lg p-3">
                            <p className="text-sm text-gray-800 font-medium">Measurable Objective:</p>
                            <p className="text-sm text-gray-700">{(recommendation.data as IEPGoal).measurableObjective}</p>
                            <p className="text-xs text-gray-600 mt-2">Target Criteria: {(recommendation.data as IEPGoal).targetCriteria}</p>
                          </div>
                        )}

                        {recommendation.type === 'accommodation' && (
                          <div className="bg-gray-50 rounded-lg p-3">
                            <p className="text-sm text-gray-800 font-medium">Implementation:</p>
                            <p className="text-sm text-gray-700">{(recommendation.data as Accommodation).implementation}</p>
                          </div>
                        )}

                        {recommendation.type === 'service' && (
                          <div className="bg-gray-50 rounded-lg p-3 grid grid-cols-2 gap-2 text-sm">
                            <div>
                              <span className="font-medium text-gray-800">Provider:</span>
                              <p className="text-gray-700">{(recommendation.data as Service).provider}</p>
                            </div>
                            <div>
                              <span className="font-medium text-gray-800">Frequency:</span>
                              <p className="text-gray-700">{(recommendation.data as Service).frequency}</p>
                            </div>
                            <div>
                              <span className="font-medium text-gray-800">Duration:</span>
                              <p className="text-gray-700">{(recommendation.data as Service).duration}</p>
                            </div>
                            <div>
                              <span className="font-medium text-gray-800">Supports Goals:</span>
                              <p className="text-gray-700">{(recommendation.data as Service).goals.join(', ')}</p>
                            </div>
                          </div>
                        )}
                      </div>
                    </div>
                  </motion.div>
                ))}
              </div>
            </motion.div>
          )}

          {currentStep === 'customize' && (
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              className="space-y-6"
            >
              <div className="text-center">
                <Edit className="w-12 h-12 text-coral-500 mx-auto mb-4" />
                <h3 className="text-xl font-bold text-gray-900 mb-2">Customize Your IEP</h3>
                <p className="text-gray-600">
                  Add additional goals, accommodations, or services to personalize the IEP.
                </p>
              </div>

              <div className="bg-amber-50 border border-amber-200 rounded-lg p-4">
                <div className="flex items-start gap-2">
                  <Lightbulb className="w-5 h-5 text-amber-600 mt-0.5" />
                  <div>
                    <h5 className="font-medium text-amber-800">Customization Coming Soon</h5>
                    <p className="text-amber-700 text-sm mt-1">
                      Custom goal and accommodation builder will be available in the next update. 
                      For now, you can proceed with the AI recommendations and make adjustments later.
                    </p>
                  </div>
                </div>
              </div>

              <div className="grid md:grid-cols-3 gap-4">
                <div className="bg-white border border-gray-200 rounded-xl p-4 text-center">
                  <Target className="w-8 h-8 text-blue-500 mx-auto mb-2" />
                  <h4 className="font-semibold text-gray-900 mb-1">Custom Goals</h4>
                  <p className="text-gray-600 text-sm">Add specific learning objectives</p>
                  <Button variant="outline" size="sm" className="mt-3" disabled>
                    Add Goal
                  </Button>
                </div>

                <div className="bg-white border border-gray-200 rounded-xl p-4 text-center">
                  <Settings className="w-8 h-8 text-green-500 mx-auto mb-2" />
                  <h4 className="font-semibold text-gray-900 mb-1">Accommodations</h4>
                  <p className="text-gray-600 text-sm">Additional support strategies</p>
                  <Button variant="outline" size="sm" className="mt-3" disabled>
                    Add Accommodation
                  </Button>
                </div>

                <div className="bg-white border border-gray-200 rounded-xl p-4 text-center">
                  <Users className="w-8 h-8 text-purple-500 mx-auto mb-2" />
                  <h4 className="font-semibold text-gray-900 mb-1">Services</h4>
                  <p className="text-gray-600 text-sm">Related services and support</p>
                  <Button variant="outline" size="sm" className="mt-3" disabled>
                    Add Service
                  </Button>
                </div>
              </div>
            </motion.div>
          )}

          {currentStep === 'review' && (
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              className="space-y-6"
            >
              <div className="text-center">
                <FileText className="w-12 h-12 text-green-500 mx-auto mb-4" />
                <h3 className="text-xl font-bold text-gray-900 mb-2">IEP Draft Ready</h3>
                <p className="text-gray-600">
                  Review your AI-generated IEP draft before saving or sharing.
                </p>
              </div>

              {/* Summary */}
              <div className="bg-gradient-to-r from-green-50 to-blue-50 rounded-xl p-6 border border-green-200">
                <h4 className="text-lg font-semibold text-gray-900 mb-4">IEP Summary</h4>
                <div className="grid md:grid-cols-3 gap-4">
                  <div className="text-center">
                    <Target className="w-8 h-8 text-blue-500 mx-auto mb-2" />
                    <p className="text-2xl font-bold text-gray-900">
                      {aiRecommendations.filter((r, i) => selectedRecommendations.has(i) && r.type === 'goal').length}
                    </p>
                    <p className="text-sm text-gray-600">Goals</p>
                  </div>
                  <div className="text-center">
                    <Settings className="w-8 h-8 text-green-500 mx-auto mb-2" />
                    <p className="text-2xl font-bold text-gray-900">
                      {aiRecommendations.filter((r, i) => selectedRecommendations.has(i) && r.type === 'accommodation').length}
                    </p>
                    <p className="text-sm text-gray-600">Accommodations</p>
                  </div>
                  <div className="text-center">
                    <Users className="w-8 h-8 text-purple-500 mx-auto mb-2" />
                    <p className="text-2xl font-bold text-gray-900">
                      {aiRecommendations.filter((r, i) => selectedRecommendations.has(i) && r.type === 'service').length}
                    </p>
                    <p className="text-sm text-gray-600">Services</p>
                  </div>
                </div>
              </div>

              {/* Next Steps */}
              <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
                <h5 className="font-medium text-blue-800 mb-2">Next Steps</h5>
                <ul className="text-blue-700 text-sm space-y-1">
                  <li>• Save this IEP draft to your child's profile</li>
                  <li>• Share with teachers when enrolling in school</li>
                  <li>• Schedule IEP team meeting for formal review</li>
                  <li>• Make adjustments based on team feedback</li>
                </ul>
              </div>
            </motion.div>
          )}
        </div>

        {/* Footer Actions */}
        <div className="bg-gray-50 px-6 py-4 flex items-center justify-between">
          {currentStep === 'analysis' && (
            <>
              <Button variant="outline" onClick={onClose}>
                Cancel
              </Button>
              <div></div>
            </>
          )}

          {currentStep === 'recommendations' && (
            <>
              <Button 
                variant="outline" 
                onClick={() => setCurrentStep('analysis')}
              >
                Back
              </Button>
              <Button
                variant="gradient"
                onClick={() => setCurrentStep('customize')}
                disabled={selectedRecommendations.size === 0}
                className="flex items-center gap-2"
              >
                Continue
                <ArrowRight className="w-4 h-4" />
              </Button>
            </>
          )}

          {currentStep === 'customize' && (
            <>
              <Button 
                variant="outline" 
                onClick={() => setCurrentStep('recommendations')}
              >
                Back
              </Button>
              <Button
                variant="gradient"
                onClick={() => setCurrentStep('review')}
                className="flex items-center gap-2"
              >
                Review IEP
                <ArrowRight className="w-4 h-4" />
              </Button>
            </>
          )}

          {currentStep === 'review' && (
            <>
              <Button 
                variant="outline" 
                onClick={() => setCurrentStep('customize')}
              >
                Back to Customize
              </Button>
              <div className="flex items-center gap-3">
                <Button
                  variant="outline"
                  onClick={() => onPreviewIEP(generateIEPDocument())}
                  className="flex items-center gap-2"
                >
                  <Eye className="w-4 h-4" />
                  Preview
                </Button>
                <Button
                  variant="gradient"
                  onClick={() => onSaveIEP(generateIEPDocument())}
                  className="flex items-center gap-2"
                >
                  <Download className="w-4 h-4" />
                  Save IEP Draft
                </Button>
              </div>
            </>
          )}
        </div>
      </motion.div>
    </div>
  );
};